version: "3.9"

services:
  scraper:
    build:
      context: .
      target: scraper
    environment:
      BINARY: scraper
    command: -redis-host=redis:6379
    networks:
    - main
    depends_on:
    - redis

  api:
    build:
      context: .
      target: api
    environment:
      BINARY: api
    command: -redis-host=redis:6379
    ports:
    - 8901
    networks:
    - main
    depends_on:
    - redis

  redis:
    image: redis
    ports:
    - 6379
    networks:
    - main

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOST: redis
    ports:
    - 8081
    networks:
    - main
    depends_on:
    - redis

networks:
  main: